# Generated by Django 6.0.7 on 2026-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_complaint_assigned_to_complaint_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="expected_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="category",
            field=models.CharField(
                choices=[
                    ("water", "Water"),
                    ("electricity", "Electricity"),
                    ("security", "Security"),
                    ("plumbing", "Plumbing"),
                    ("waste", "Waste Management"),
                    ("cleaning", "Cleaning"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
