# Generated by Django 6.0.7 on 2026-08-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_property_complaint_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="resident_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
