# Generated by Django 6.0.7 on 2026-08-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_profile_resident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
