# Generated by Django 6.0.7 on 2026-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("resident", "Resident"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="resident",
                max_length=20,
            ),
        ),
    ]
