### Get JWT Token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "wunmi",
  "password": "124578"
}

###
POST http://127.0.0.1:8000/api/residents/assign-property/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NTgxMzg2LCJpYXQiOjE3ODc1ODEwODYsImp0aSI6ImI2Zjc3MzkwOWNjYTRkMzBiNzcxZjZmNWYzMzhlNTE4IiwidXNlcl9pZCI6IjQifQ.XYGWZ9t9tmzXYIpS4qEMep4_Gh0kvBmzf8k3g6gZlzQ
Content-Type: application/json

{
    "resident_id": "R001",
    "property_id": "P001",
    "title": "Water Leakage",
    "description": "There is a water leakage in the bathroom.",
    "category": "Plumbing",
    "priority": "High"
}